name:                bombastus
version:             0.1.0
license:             GPL-3.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2020 barsanges

extra-source-files:
- README.md

synopsis:            Some complex science
description:         Please see the README

dependencies:
- base
- time
- vector

library:
  source-dirs: src